### ISSUE TITLE
Support for Local Storage

### ISSUE THREAD

**Issue by jkersbergen-redhat** [sagyvolkov/sherlock#1]
Please add support for Local Storage to test underlying storage for comparison.

**Comment by sagyvolkov** [comment]
Sherlock can work easily with local storage and the Local Storage Operator (LSO), just set STORAGE_CLASS to the *file* based LSO storage class.
You do need to remember that there is a relationship between the number of DBs and the number of PVCs, and in the case of local storage that means that DB_PER_WORKER must be equal to the number of block devices that exists in each node/worker you want to create databases.
